apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: cluster-onboard-location
  description: Location to import all cluster-onboard catalog components
spec:
  targets:
    - ./.platform/*.yaml
